### ISSUE TITLE
Add action button to contribute palettes to palettes library

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/huehive-mobile-app#113]
Write documentation on how to add new palettes to library and add link to the contribution in the action button in PaletteLibraryScreen.
![Screenshot from 2020-10-22 22-14-16](https://user-images.githubusercontent.com/5221843/96903861-fbbb7500-14b3-11eb-887b-bc60b15c0409.png)

**Comment by vivianxu1230** [comment]
Hi, I'd like to work on this! Would it be better for there to be a tutorial located and accessed through an icon in the upper right corner of the nav bar, instead of accessed from the action button (+) on the home screen?

**Comment by bhujoshi** [comment]
@vivianxu1230 thanks for picking this. We have the main action on any screen using an action button so I think the action button is a better choice here for the sake of consistency.

**Comment by vivianxu1230** [comment]
@bhujoshi Great! Thanks for assigning me. So to clarify, a button needs to be added above the purple button with the image icon, and linked to that button should be documentation on how to use each of the other action items (the palette feature by uploading an image, getting generate palettes from a color, creating new palette)?

**Comment by bhujoshi** [comment]
@vivianxu1230 Please share your email on bhuwanchandra.it@gmail.com I will add you in slack group and we will discuss there.
