### ISSUE TITLE
HWB is overflowing on color detail page in android app.

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/huehive-mobile-app#77]
![Screenshot from 2020-07-26 11-33-55](https://user-images.githubusercontent.com/5221843/88472767-11acae80-cf34-11ea-94fa-0c9e3075109b.png)

**Comment by bhujoshi** [comment]
**Step to reproduce** 
**Step 1. ** Open the given URL  and save the color palette on the android app.  https://croma.app/#/Main/SavePalette?name=Croma%20example%20palette&colors=%5B%7B%22color%22%3A%22%23797979%22%7D%2C%7B%22color%22%3A%22%23c9ef5b%22%7D%2C%7B%22color%22%3A%22%23ebef5c%22%7D%2C%7B%22color%22%3A%22%23f0675f%22%7D%5D

**Step 2** View color details of #797979 and you will face the overflow problem HWB.

**Comment by parthg2211** [comment]
Hello , I was checking in the "Get palette form colour" for this but I didnt see the info for that colour. I only saw other colour codes which were similar to this colour.
<img width="287" alt="Screenshot 2023-05-09 at 11 05 56 PM" src="https://github.com/croma-app/croma/assets/49000418/916cf4a0-178d-4eba-98f0-0b5ae35914bf">

I have attached a ss of the screen I am seeing.

**Comment by mtalhabaig3** [comment]
Hi @kamalkishor1991 , I solved the issue but i had to make some changes in one of the modules in the node modules .i.e: at node_modules/pigment/models/hwb.js

<img width="1440" alt="Screenshot 2023-05-25 at 4 23 53 PM" src="https://github.com/croma-app/croma/assets/57634631/0a91d578-7f4e-472e-8695-c9470c74b23e">

But now how would i push the changes as node modules has been put in .gitignore. Need guidence

**Comment by kamalkishor1991** [comment]
changes should be made outside node_modules. node_modules contain libraries
In this case you should make changes in components/ColorDetails.js

**Comment by mtalhabaig3** [comment]
Okay
