### ISSUE TITLE
Combine camera and image color extraction to a single button

### ISSUE THREAD

**Issue by kamalkishor1991** [croma-app/huehive-mobile-app#99]
It should be part of the action button with 2 options as a popover to select either image or camera.

**Comment by toremielck** [comment]
What do you mean exactly by selecting a color by using the camera?

**Comment by kamalkishor1991** [comment]
@toremielck croma has a function where you can tap on a screen to pick color using the camera. It is the top option in FAB.
![image](https://user-images.githubusercontent.com/5221843/142712024-6522a82d-10c5-4cfb-89f7-45d83a7dd74f.png)

**Comment by kamalkishor1991** [comment]
we have combined options to pick colors from image and automatically parse colors from an image now. We no longer need to combine camera and image. Closing.

**Comment by kamalkishor1991** [comment]
https://github.com/croma-app/huehive-mobile-app/pull/210
